name: infra-deploy
run-name: infra-deploy-${{ github.ref_name }}-${{ github.event_name }}

on:
  push:
    branches:
      - develop
      - main
    paths:
      - infra/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ENV: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}

jobs:
  what-if:
    runs-on: ubuntu-latest
    environment: ${ENV}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Azure Login (OIDC)
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: What-if
        run: |
          az deployment group what-if \
            --name infra-${ENV}-${GITHUB_RUN_NUMBER} \
            --resource-group rg-${ENV} \
            --template-file infra/bicep/main.bicep \
            --parameters infra/bicep/params/${ENV}.bicepparam

  deploy:
    needs: what-if
    runs-on: ubuntu-latest
    environment: ${ENV}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Azure Login (OIDC)
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy
        run: |
          az deployment group create \
            --mode Incremental \
            --name infra-${ENV}-${GITHUB_RUN_NUMBER} \
            --resource-group rg-${ENV} \
            --template-file infra/bicep/main.bicep \
            --parameters infra/bicep/params/${ENV}.bicepparam